### PR TITLE
Fix Netlify deployment

### PR DESCRIPTION
**Pull request by nwtgck**

### CODE REVIEW

**Comment by nwtgck** [comment]
And we have another problem "Missing access token" below in the actions.
image
(see: https://github.com/kaihendry/dabase.com/pull/2/checks?check_run_id=461553156)

**Comment by kaihendry** [comment]
"GitHub automatically creates a GITHUB_TOKEN secret to use in your workflow." .... no? https://help.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token

**Comment by nwtgck** [comment]
@kaihendry Yes. But "Missing access token" is about Netlify token I think.

**Comment by kaihendry** [comment]
It's all set I think:

image

**Comment by kaihendry** [comment]
Appears to work on a test I made here: https://github.com/kaihendry/dabase.com/pull/3#issuecomment-589909534

Perhaps some permission problem? Idk

**Comment by nwtgck** [comment]
@kaihendry It seems well...
I don't figure out the reason. Could you make sure NETLIFY_AUTH_TOKEN and NETLIFY_SITE_ID are the right values?

My repositories and another author repositories using `actions-netlify` work well.
- https://github.com/nwtgck/piping-ui-web/runs/459425185?check_suite_focus=true
- https://github.com/tiangolo/fastapi/runs/449278888?check_suite_focus=true

**Comment by nwtgck** [comment]
> Appears to work on a test I made here: [#3 (comment)](https://github.com/kaihendry/dabase.com/pull/3#issuecomment-589909534)
> 
> Perhaps some permission problem? Idk

Greate! It seems some permission problem.

**Comment by kaihendry** [comment]
Thank you for your help.

Perhaps it's because you modified the workflow and Github actions doesn't like that?

Thanks again!

**Pull request closed without merging**
