### PR TITLE
Testing actions-comment-run

### PR DESCRIPTION
**Pull request by kaihendry**
https://github.com/nwtgck/actions-comment-run/

### CODE REVIEW

**Comment by kaihendry** [comment]
@github-actions run

```js
(async () => {
  await postComment("hello, world");
})();
```

**Comment by mirrorsuck** [comment]
@github-actions run

```js
(async () => {
  await postComment("hello, world from another user not in the project");
})();
```

**Comment by mirrorsuck** [comment]
@github-actions run

<details>
<summary>LGTM 👍 </summary>

```js
(async () => {
  const res = await fetch("https://lgtm.in/g", {
    redirect: 'manual'
  });
  const webSiteUrl = res.headers.get('location');
  const picUrl = new URL(webSiteUrl);
  picUrl.pathname = picUrl.pathname.replace("/i/", "/p/");
  postComment(`![LGTM](${picUrl.href})`);
})();
```
</details>

**Comment by kaihendry** [comment]
@github-actions run

```js
await postComment("hello, world");
```

**Comment by kaihendry** [comment]
@github-actions run

<details>
<summary>LGTM 👍 </summary>

```js
const res = await fetch("https://lgtm.in/g", {
  redirect: 'manual'
});
const webSiteUrl = res.headers.get('location');
const picUrl = new URL(webSiteUrl);
picUrl.pathname = picUrl.pathname.replace("/i/", "/p/");
postComment(`![LGTM](${picUrl.href})`);
```
</details>

**Comment by kaihendry** [comment]
@github-actions run

```js
await postComment("hello, world");
```

**Pull request closed without merging**
